name = "cloudflare-worker-s3"
type = "webpack"
workers_dev = true
compatibility_date = "2021-11-07"

[env.dev]
zone_id = ""
route = ""
vars = { "AWS_ACCESS_KEY_ID" = "", "AWS_REGION" = "", "AWS_S3_BUCKET" = "", "AWS_SECRET_ACCESS_KEY" = "" }
# secrets = ["AWS_ACCESS_KEY_ID", "AWS_REGION", "AWS_S3_BUCKET", "AWS_SECRET_ACCESS_KEY"]
# kv_namespaces = [
#     { binding = "KV", id = "" }
# ]